config/routes.rb
Blog::Application.routes.draw do
  get "store/index"
   resources :articles do
   resources :comments
  end

   root :to => "store#index", :as => 'store'
   match ':controller(/:action(/:id(.:format)))'
end

app/models/article.rb
class Article < ActiveRecord::Base
 validates :title, :presence =>true
 validates :body, :presence => true
 has_many :comments
 cattr_reader :per_page
  @@per_page = 10
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 belongs_to :article
 validates :name, :email, :body, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  
  before_filter :authenticate
  
  def index
    @articles = Article.paginate(:page => params[:page],:per_page => 5, :order => "published_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def authenticate
  	authenticate_or_request_with_http_basic('Administration') do|username, password|
  	username == 'adminka' && password = 'adminka'
  	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_filter :load_article
 before_filter :authenticate, :only => :destroy


  def create
    @comment = @article.comments.new(params[:comment])
    if @comment.save
      render :action => "thanks", :notice => 'Thanks for your comment'
    else
      render :action => "unable", :alert => 'Unable to add comment'
    end
  end
  
  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    render :action => "destroy", :notice => 'Comment deleted'
  end
  
  private
    def load_article
      @article = Article.find(params[:article_id])
    end
    
    def authenticate
    	authenticate_or_request_with_http_basic('Administrator') do |username, password|
    	username == 'comment' && password = 'comment'
    	end
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  @articles = Article.paginate(:page => params[:page],:per_page => 5, :order => "published_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
  <h3>
    <%= link_to article.title, article %>
  </h3>
  <%= raw textilize(article.body) %>
<span class='actions'>
      <%= link_to "Edit", edit_article_path(article) %>
      <%= link_to "Delete", article, :confirm => "Are you sure?", :method => :delete %>
      <%= link_to 'Back', articles_path %>
    </span>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<p><%= link_to 'Back', articles_path %></p>


<%= render 'form' %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <h1><%= article.title %></h1>
  <h5><%= article.published_at %></h5>
  <p><%= raw textilize(article.body) %></p>

    <%= link_to 'Show', article %>
    <%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
<br />

<%= link_to 'New Article', new_article_path %>
<%= will_paginate @articles%>
  

app/views/articles/index.html_old.erb
<html>
<head>
<title> From love with myscript.biz</title>
</head>
<body>
<div id="header"><h1>My blog</h1></div>

<div id="infinitum">
    <p><strong>Navigation<br />
      </strong><a href="http://myscript.biz">Home</a></p>
    <p><a href="#">Colophon</a></p>
    <p><a href="#">Photography</a></p>
    <p><a href="#">Portfolio</a></p>
    <p><a href="#">Contact</a><strong><br />
      <br />
      Search</strong><br />
    </p>
    <form name="form1" id="form1" method="post" action="#">
      <input type="text" name="textfield" />
    </form>
    <p>&nbsp;</p>
    <p><strong>Monthly Archives</strong></p>
    <p><a href="#">June 2005 <br />
      May 2005</a></p>
    <p><a href="#">April 2005</a></p>
    <p><a href="#">March 2005</a></p>
    <p> <strong><br />
      Categories</strong></p>
    <p><a href="#">Discussion</a></p>
    <p><a href="#">Jokes</a></p>
    <p><a href="#">Typography</a></p>
    <p><a href="#">Design</a></p>
    <p><a href="#">CSS</a></p>
    <p><a href="#">XHTML</a></p>
    <p><a href="#">Politics</a></p>
    <p>&nbsp;</p>
    <p><strong>Feeds</strong></p>
    <p><a href="#">RSS</a></p>
    <p><a href="#">Atom</a></p>
    <p>&nbsp;</p>
    <p><strong>Disclaimers</strong></p>
    <p>&copy; Biotin</p>
    <p><a rel="nofollow" target="_blank" href="http://myscript.biz">Redesign by Biotin</a></p>
    <p>Design by Smallpark.</p>
    <p>&nbsp;</p>
  </div>
  

<div id="container">
   <div class="text">
   
<% @articles.each do |article| %>
  <h1><strong>  <td><%= article.title %></strong></h1>
  <h2><strong><%= article.published_at %></strong></h1>
  <p><%= article.body %></p>

    <%= link_to 'Show', article %>
    <%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
<br />

<%= link_to 'New Article', new_article_path %>
  </div>
</div>
</body>
</html>

app/views/articles/new.html.erb
<h1>New article</h1>

<p><%= link_to 'Back', articles_path %></p>

<%= render 'form' %>

app/views/articles/show.html.erb
<%= render @article %>
<h3>Comments</h3>
<div id="comments">
  <%= render @article.comments %>
</div>

<%= link_to "new comment", new_article_comment_path(@article, :format => :js), :remote => true, :id => 'new_comment_link' %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p>
    <%= comment.name %> &lt;<%= comment.email %>&gt; said:
    <span class='actions'>
      <%= link_to 'Delete', [@article, comment], :confirm => 'Are you sure?', :method => :delete %>
    </span>
  </p>
  <%= comment.body %>
<% end %>

app/views/comments/_thanks.html.erb
Thanks for comment.

app/views/comments/comment_store.html.erb
<%= div_for @comment do %>
  <p>
    <%= comment.name %> &lt;<%= comment.email %>&gt; said:
  </p>
  <%= comment.body %>
<% end %>

app/views/comments/destroy.html.erb
Be happy, Comment deleted!

app/views/comments/new.html.erb
<%= form_for([@article, @article.comments.new]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Add' %>
  </div>
<% end %>

app/views/comments/new.js.erb
$("<%= escape_javascript render(:file => 'comments/new.html.erb') %>").insertAfter('#comments');
$('#new_comment_link').hide();

app/views/comments/thanks.html.erb
Thanks for coomment.

app/views/comments/unable.html.erb
Sorry, Unable to add comment!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>From love with myscript.biz</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.4.min', 'rails' %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header"><h1>My blog</h1></div>

<div id="infinitum">
    <p><strong>Navigation<br />
    </strong><%= link_to "Home", :action => "index" %></p>
    <p><%= link_to "Photography", :action => "index" %></p>
    <p><%= link_to "Portfolio", :action => "index" %></p>
    <p><%= link_to "Contact", :action => "index" %></ p>
      <br />
    <p>&nbsp;</p>
    <p><strong>Monthly Archives</strong></p>
    <p><a href="#">June 2005</a><p>
    <p><a href="#">May 2005</a></p>
    <p><a href="#">April 2005</a></p>
    <p><a href="#">March 2005</a></p>
    <p> <strong><br />
      Categories</strong></p>
    <p><a href="#">Discussion</a></p>
    <p><a href="#">Jokes</a></p>
    <p><a href="#">Typography</a></p>
    <p><a href="#">Design</a></p>
    <p><a href="#">CSS</a></p>
    <p><a href="#">XHTML</a></p>
    <p><a href="#">Politics</a></p>
    <p>&nbsp;</p>
    <p><strong>Feeds</strong></p>
    <p><a href="#">RSS</a></p>
    <p><a href="#">Atom</a></p>
    <p>&nbsp;</p>
    <p><strong>Disclaimers</strong></p>
    <p>&copy; Biotin</p>
    <p><a rel="nofollow" target="_blank" href="http://myscript.biz">Redesign by Biotin</a></p>
    <p>&nbsp;</p>
  </div>
  

<div id="container">
   <div class="text">

<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>

<%= yield %>



</div>
</div>
</body>
</html>

app/views/store/index.html.erb
<% @articles.each do |article| %>
  <h1><%= link_to article.title,:action => "show",:id => article %></h1>
  <h5><%= article.published_at %></h5>
  <p><%= raw textilize(article.body) %></p>
   <p></p>
   <%= link_to "Show", :action => "show",:id => article %><br />
  <% end %>
<br />

<%= will_paginate @articles%>

app/views/store/show.html.erb
<%= div_for @article do %>
  <h3>
    <%= link_to @article.title, :action => "show",:id => @article %>
  </h3>
  <%= raw textilize(@article.body) %>
  <h3>Comments</h3>
<div id="comments">
  <%= render @article.comments%>
</div>
 <% end %>


<%= link_to "new comment", new_article_comment_path(@article, :format => :js), :remote => true, :id => 'new_comment_link' %>